version: "3.8"

services:

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks: [ kc-net ]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    depends_on: [ keycloak-db ]
    networks: [ kc-net ]


  app-db:
    image: postgres:16
    environment:
      POSTGRES_DB: oshapp
      POSTGRES_USER: oshapp
      POSTGRES_PASSWORD: oshapp
    volumes:
      - oshapp-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [ kc-net ]

networks:
  kc-net:

volumes:
  keycloak-db-data:
  oshapp-db-data:
