spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/oshapp
    username: oshapp
    password: oshapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oshapp

  mail:
    host: smtp.gmail.com
    port: 587
    username: badrcheouai48@gmail.com 
    password: dxph mfrk jjsh zbms      
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: oshapp-backend