# Configuration Spring Boot unifiée (YAML)
# - Par défaut : profil local (hors Docker)
# - Profil 'docker' : activé automatiquement dans Docker Compose

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/oshapp
    username: oshapp
    password: oshapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oshapp
  mail:
    host: smtp.mock.local
    port: 1025
    username: dummy
    password: dummy
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

keycloak:
  auth-server-url: http://localhost:8080
  realm: oshapp
  client-id: oshapp-backend
  client-secret: a8jP4kXYvjxzfZn9K9XB7CPQMVHsNwBZ

server:
  port: 8082
  ssl:
    enabled: false

logging:
  level:
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ThisIsTheNewOshappSecretKeyForJWTTokenGenerationWithMinimum512BitsSecurity
    expirationMs: 86400000

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: oshapp-backend

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://app-db:5432/oshapp
    username: oshapp
    password: oshapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/oshapp
  mail:
    host: smtp.mock.local
    port: 1025
    username: dummy
    password: dummy
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8082
  ssl:
    enabled: false

logging:
  level:
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ThisIsTheNewOshappSecretKeyForJWTTokenGenerationWithMinimum512BitsSecurity
    expirationMs: 86400000

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: oshapp-backend